// src/components/react/Canvas.tsx
import type { RunType } from '~/workers/types'
import CanvasWorker from '~/workers/canvas.worker?worker'
import { PayloadType } from '~/workers/canvas.worker.constants'
import { useWorker } from '~/composables/useWorker'

interface CanvasProperties {
  width?: number
  height?: number
}

export const Canvas = ({ width = 800, height = 450 }: CanvasProperties) => {
  const { isSupported, post, terminate } = useWorker(new CanvasWorker())
  const [fps, setFps] = useState(30)

  const canvasElementRef = useCallback((value: HTMLCanvasElement) => {
    const canvas = value?.transferControlToOffscreen()

    if (!canvas) {
      throw new Error('Canvas cannot be transferred')
    }

    post({ type: 'init', value: canvas }, [canvas])
    post({ type: 'start' })
  }, [])

  const onChangeFps = useCallback(({ target: { value, valueAsNumber } }: React.ChangeEvent<HTMLInputElement>) => {
    setFps(valueAsNumber)
    post({ type: 'fps', value })
  }, [])

  const run = useCallback((type: RunType) => post({ type }), [])
  const start = () => run(PayloadType.Start)
  const stop = () => run(PayloadType.Stop)

  useEffect(() => terminate, [])

  if (!isSupported) {
    return <div>Webworker and OffscreenCanvas not suported</div>
  }

  return (
    <div>
      <div className="flex gap-4 flex-col">
        <span className="text-center">fps: {fps}</span>
        <input type="range" min="1" max="60" value={fps} onChange={onChangeFps} />
      </div>
      <canvas width={width} height={height} ref={canvasElementRef} className="rounded my-4" />
      <div className="flex gap-4 justify-center">
        <button className="btn-teal" onClick={start}>
          Start
        </button>
        <button className="btn-amber" onClick={stop}>
          Stop
        </button>
      </div>
    </div>
  )
}

// src/components/vue/Canvas.vue
<script setup lang="ts">
import type { RunType } from '~/workers/types'
import CanvasWorker from '~/workers/canvas.worker?worker'
import { PayloadType } from '~/workers/canvas.worker.constants'
import { useWorker } from '~/composables/useWorker'

interface ComponentProps {
  width?: number
  height?: number
}

const { width = 800, height = 450 } = defineProps<ComponentProps>()

const { isSupported, post, terminate } = useWorker(new CanvasWorker())
const canvasElementRef = $ref<HTMLCanvasElement | null>(null)
const fps = $ref(30)

const run = (type: RunType) => post({ type })
const start = () => run(PayloadType.Start)
const stop = () => run(PayloadType.Stop)

watch(
  () => canvasElementRef,
  (value) => {
    const canvas = value?.transferControlToOffscreen()

    if (!canvas) {
      throw new Error('Canvas cannot be transferred')
    }

    post({ type: 'init', value: canvas }, [canvas])
    post({ type: 'start' })
  },
)

watch(
  () => fps,
  (value) => post({ type: 'fps', value }),
)

onUnmounted(terminate)
</script>

<template>
  <div v-if="!isSupported">Webworker and OffscreenCanvas not suported</div>
  <div v-if="isSupported">
    <div class="flex gap-4 flex-col">
      <span class="text-center">fps: {{ fps }}</span>
      <input type="range" min="1" max="60" v-model.number="fps" />
    </div>
    <canvas :width="width" :height="height" ref="canvasElementRef" class="rounded my-4" />
    <div class="flex gap-4 justify-center">
      <button class="btn-teal" @click="start">Start</button>
      <button class="btn-amber" @click="stop">Stop</button>
    </div>
  </div>
</template>
